# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('registrationDeadline', models.DateTimeField()),
                ('maxTeams', models.IntegerField(default=8)),
            ],
        ),
    ]
