# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thurdsday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday')], default='U', max_length=1),
        ),
    ]
