# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('League', '0001_initial'),
        ('Team', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('homeScore', models.IntegerField(blank=True, null=True)),
                ('awayScore', models.IntegerField(blank=True, null=True)),
                ('gameNumber', models.IntegerField(blank=True, null=True)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='Team.Team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='Team.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.Referee')),
            ],
        ),
    ]
