# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('League', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='Person.Player')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='Person.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='Person.Player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='Person.Player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='Person.Player')),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='Person.Player')),
                ('player6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='Person.Player')),
                ('player7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='Person.Player')),
                ('player8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='Person.Player')),
                ('player9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='Person.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.League')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.Roster')),
            ],
        ),
    ]
