# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='Person.Player'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='Person.Player'),
        ),
    ]
